libreoffice/backing_left-blankon.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_right-blankon.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_rtl_left-blankon.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_rtl_right-blankon.png /usr/lib/libreoffice/program/shell/
libreoffice/backing_space-blankon.png /usr/lib/libreoffice/program/shell/
libreoffice/intro.png /usr/lib/libreoffice/program/
libreoffice/flat_logo.svg /usr/lib/libreoffice/program/
libreoffice/sofficerc /etc/libreoffice/
